// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'controller.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$realtimeArrivalNotifierHash() =>
    r'539b11c0ba2a751f508cc5d2aa39c2dd199bb6f0';

/// See also [RealtimeArrivalNotifier].
@ProviderFor(RealtimeArrivalNotifier)
final realtimeArrivalNotifierProvider = AutoDisposeNotifierProvider<
    RealtimeArrivalNotifier, AsyncValue<Autogenerated>>.internal(
  RealtimeArrivalNotifier.new,
  name: r'realtimeArrivalNotifierProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$realtimeArrivalNotifierHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$RealtimeArrivalNotifier
    = AutoDisposeNotifier<AsyncValue<Autogenerated>>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member
